### ISSUE TITLE
Is there a way to exclude files from local project (not vendor)?

### ISSUE THREAD

**Issue by mrself** [mcaskill/composer-plugin-exclude-files#1]

**Comment by mcaskill** [comment]
Hi @mrself,

This plugin only targets files in a package's `autoload.files` property.

By local project, do you mean the root package?
As in, you want to exclude a file you specified in the root package's `autoload.files` property?

**Comment by mrself** [comment]
Yes, I mean root package. But no, I did not specified that file in `autoload.files`. It is simple class, defined under `autoload.psr-4` namespace.

So, if 

>This plugin only targets files in a package's autoload.files property.

then my want can not be done with your plugin.

**Comment by mcaskill** [comment]
I don't understand what you are trying to achieve.

PSR-4 is a way to autoload classes from file paths. As long as you don't instantiate the class (e.g., `new \Foo\Baz`) or avoid triggering the autoload mechanism in functions like `class_exists( 'Foo\\Baz', false )`, the file won't be loaded.

---

> then my want can not be done with your plugin.

Yeah, this Composer plugin is designed to disable files that a vendor package needs to have included as soon as the vendor-dir is included in one's project.

**Comment by mrself** [comment]
Actually I am not sure if I am doing the things in the right way. I want to use the class but so that it will be required in a specific place of my code. You are right, if I instantiate thae class it will be autoloaded. That is what I am trying to avoid. I want the composer to ignore that file so that to require it manually. Does it make sense?

But again, you already let me know that you plugin is not what I need. Anyway, thanks for your response.

**Comment by mcaskill** [comment]
Composer uses PHP's [autoloading mechanism](http://php.net/manual/en/language.oop5.autoload.php) which only loads the file when needed.

So, the class is being instantiated too early or out of turn? Like before another dependency is ready? I'd recommend you look into the conditions that trigger the class' instantiation, add some checks to ensure your class is ready.

Anyway, good luck with your project.
