### ISSUE TITLE
Support separate rules for `autoload-dev`

### ISSUE THREAD

**Issue by top-master** [mcaskill/composer-plugin-exclude-files#10]
I would like to organize my `PHPUnit` tests so that, tests get placed next to what they’re testing.

This approach is used by a many popular frameworks in the `JavaScript` world.

But for `PHP`, that would require `composer.json` like:
```
{
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "exclude-from-files": [
            "../app/**/*Test.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
}
```

Hence it would be nice if `autoload` and `autoload-dev` could each have a separate `exclude-from-files` list supported,
instead-of or beside current-structure:
```
{
    "extras": {
        "exclude-from-files": [
            "../app/**/*Test.php"
        ]
    }
}
```

However, are even `**` and `*Test.php` patterns supported, or does that need separate feature request?

**Comment by mcaskill** [comment]
The initial implementation of this plugin supported `autoload.exclude-from-files` to match the native `autoload.exclude-from-classmap` but Composer discourages (#8) adding options outside of `extra`.

Currently, the plugin is designed to only ignore from the `files` autoloading mechanism.

Your request appears to be about ignoring from any of Composer's autoloading entry-points. Which is a potential idea but outside of the scope of this plugin's namesake.

I'm under the impression `autoload.exclude-from-classmap` would work for your situation. I think PHPUnit scans and executes `*Test.php` files regardless of inclusion in Composer autoload mappings.

```json
{
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "exclude-from-classmap": [
            "app/**/*Test.php"
        ]
    }
}
```

**Comment by top-master** [comment]
The problem with `exclude-from-classmap` (which's a built-in Composer feature) is that, it's name was confusing, and I thought it supports only class-names (instead of file-names).

But I checked, and `app/**/*Test.php` pattern works just fine (with my Composer version 2.0.8 at least).
And `PHPUnit` had no issues with:
```
    <testsuites>
        <testsuite name="App">
            <directory suffix="Test.php">./app/**/</directory>
        </testsuite>
    </testsuites>
```

---

Also, the files seem to be only removed from `autoload`, I mean, the doc-comment's references work even after adding `exclude-from-classmap` settings, at least in my IDE, but I did not check what the doc-generator's output is for below:
```php
<?php

namespace App\Http\Controllers;

class MyController
{
    /**
     * @see MyControllerTest::testMyMethod_shoudDoSomethingCool()
     */
    public function myMethod()
    {
        return 'my-cool-result';
    }
}
```
>But if doc-generator fails, we maybe could use absolute path instead, like:
>```
>\App\Http\Controllers\MyControllerTest::testMyMethod_shoudReturnTrue()
>```
