### ISSUE TITLE
Not working with composer 2.5.7 (with 2.5.6 all is ok)

### ISSUE THREAD

**Issue by RomanNebesnuyGC** [mcaskill/composer-plugin-exclude-files#11]
<img width="1276" alt="CleanShot 2023-05-24 at 17 38 24@2x" src="https://github.com/mcaskill/composer-plugin-exclude-files/assets/77343542/d9c4b977-d4f2-4617-b6fc-238680e69738">

**Comment by mcaskill** [comment]
Fixed in [3.0.1](https://github.com/mcaskill/composer-plugin-exclude-files/releases/tag/v3.0.1).

Thanks!
