### ISSUE TITLE
 Can the plugin support excluding folders?

### ISSUE THREAD

**Issue by cxcatir** [mcaskill/composer-plugin-exclude-files#16]
### Is your feature request related to a problem? Please describe.

Some folders contain numerous files, making it difficult to list them one by one. Is it possible to implement functionality to exclude certain folders?

### Describe the solution you'd like

It might be possible to define such a format in the "extra" section of the composer.json file, allowing for the exclusion of specified folders.

```
    "extra": {
        "exclude-from-folders": [
            "illuminate/support/"
        ]
    },
```

**Comment by mcaskill** [comment]
That's a good idea. When I have a chance I'll explore possible solutions.

Taking [laravel/framework](https://github.com/laravel/framework/blob/v11.5.0/composer.json#L128-L134) for example, I would probably just add glob support to `exclude-from-files`:

```json
"extra": {
    "exclude-from-files": [
        "laravel/framework/src/*/helpers.php"
    ]
}
```

Thanks

**Comment by mcaskill** [comment]
@cxcatir Can you test out the `main` branch (522d75f) and confirm this works as intended?

**Comment by cxcatir** [comment]
@mcaskill The plugin test looks fine. But I think I'm getting something wrong and it's not solving my requirement scenario.

I want to develop a package, and the tests inside pacakge will have a complete application and install the package I'm developing, using the path repository.
In the application, composer dump auto load encounters an infinite loop. I thought that using this plugin to exclude the test folder of the test application would solve the problem, but it didn't!

```
development-package
--test
----application which installs development-package
```

I think I still need to re-learn how composer works. But thanks for the new glob support!
