### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by richwandell** [mcaskill/composer-plugin-exclude-files#2]
I am trying to use this plugin on windows but it doesn't seem to exclude files. 

```
  "autoload": {
    "exclude-from-files": [
      "athari/yalinqo/YaLinqo/Linq.php"
    ]
  }
```

Works correctly on OSX and Ubuntu but not windows.

**Comment by mcaskill** [comment]
Hi @richwandell,

I apologize, I have not tested this plugin myself on Windows.
I'll try to look into it once I get my hands on a Windows OS.
If you figure it out in the interim, I can apply the fix.

Thanks for spotting this, at least.

Three questions:
1. What version of Windows are you on?
2. What terminal are you using to interact with Composer?
3. What version of PHP is Composer using?

Much appreciated

**Comment by richwandell** [comment]
@mcaskill sorry for not getting back to you I have been very busy lately. When I get some time I plan to look into this on windows and maybe I will send you a fix.

**Comment by mcaskill** [comment]
@richwandell I'm sorry it took so long to resolve this issue.
I've pushed a new release (v1.1.0) that merges a fix for this.
I hope it works well.
