### ISSUE TITLE
Exclude helpers from Laravel 5.7

### ISSUE THREAD

**Issue by zorca** [mcaskill/composer-plugin-exclude-files#4]
I tried to exclude the helper file from Laravel 5.7. I need it to run Laravel functionality on Wordpress.
My code:
`
        "exclude-from-files": [
            "laravel/framework/src/Illuminate/Foundation/helpers.php"
        ]
`
But it didn't work.
P. S. If it is easy, pls add the output of the package exception messages, if it is found.

**Comment by mcaskill** [comment]
Hi @zorca,

The following works on my end to exclude Illuminate's Foundation helpers:

```json
"extra": {
    "exclude-from-files": [
        "laravel/framework/src/Illuminate/Foundation/helpers.php"
    ]
}
```

Can you verify that helpers file is _not_ in the array found in: `vendor/composer/autoload_files.php`.

If the file is present, try regenerating your autoloader with:

```console
composer dump-autoload
```

**Comment by zorca** [comment]
I think this is a problem with Windows.
#3

**Comment by zorca** [comment]
#5 Windows path fix

**Comment by nmeri17** [comment]
> Hi @zorca,
> 
> The following works on my end to exclude Illuminate's Foundation helpers:
> 
> ```json
> "extra": {
>     "exclude-from-files": [
>         "laravel/framework/src/Illuminate/Foundation/helpers.php"
>     ]
> }
> ```
> 
> Can you verify that helpers file is _not_ in the array found in: `vendor/composer/autoload_files.php`.
> 
> If the file is present, try regenerating your autoloader with:
> 
> ```
> composer dump-autoload
> ```

You are my hero. Please state on the README that full path to file relative to vendor is what should be used (not its namespaced name or relative to the project itself). At least, that's what has worked for me on Windows

I also had to dump autoload to get it working. Thank you so much

**Comment by mcaskill** [comment]
Good point about confusion in the case of laravel/framework vs illuminate/support.
I'll update the README. Thanks.
