### ISSUE TITLE
Config should go into extra key

### ISSUE THREAD

**Issue by schlessera** [mcaskill/composer-plugin-exclude-files#8]
The way the configuration options are currently added to the `autoload` key in the `composer.json` file is incorrect, and causes the Composer files to not be validatable anymore.

Plugins should add all of their configuration to the `extra` key in the `composer.json` file instead, that's what this is for: https://getcomposer.org/doc/04-schema.md#extra

For backwards compatibility, the old key could still be supported, but users should be encouraged to move all configuration data to the `extra` key instead.

**Comment by mcaskill** [comment]
Thanks @schlessera! It was a silly decision on my part to allow one to use it from `autoload`.
I've been meaning to remove it and will do so as soon as possible.
